In [ ]:
import pandas as pd

In [1]:
import numpy as np

In [3]:
df = pd.read_csv('melb_data.csv')

In [4]:
df

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18391,23540,Williamstown,8/2 Thompson St,2,t,622500.0,SP,Greg,26/08/2017,6.8,...,2.0,1.0,NaN,89.0,2010.0,NaN,-37.86393,144.90484,Western Metropolitan,6380.0
18392,23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
18393,23544,Yallambie,17 Amaroo Wy,4,h,1100000.0,S,Buckingham,26/08/2017,12.7,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
18394,23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
18395,23546,Yarraville,33 Freeman St,4,h,1050000.0,VB,Village,26/08/2017,6.3,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

In [ ]:
df_pm5550000 = df[df['Price'] > 5550000]

In [6]:
df_pm1000000

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
4551,5867,Kew,7 Wimba Av,5,h,6240000.0,S,Jellis,3/09/2016,5.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Southern Metropolitan,10331.0
4599,5937,Kew,15 Barry St,6,h,6500000.0,S,Jellis,13/08/2016,5.6,...,6.0,3.0,1334.0,365.0,1890.0,Boroondara,-37.80290,145.02670,Southern Metropolitan,10331.0
7184,9264,South Yarra,18 Avoca St,4,h,5700000.0,S,Castran,12/11/2016,3.3,...,2.0,0.0,292.0,272.0,1880.0,Stonnington,-37.83770,144.98940,Southern Metropolitan,14887.0
8143,10451,Toorak,17 Albany Rd,3,h,6250000.0,S,Kay,15/10/2016,4.6,...,3.0,2.0,564.0,342.0,2000.0,Stonnington,-37.84860,145.02440,Southern Metropolitan,7217.0
9589,12316,Brighton,161 Church St,5,h,5800000.0,PI,Castran,8/04/2017,11.2,...,4.0,4.0,1276.0,NaN,1880.0,Bayside,-37.91640,144.99740,Southern Metropolitan,10579.0
9754,12539,Canterbury,49 Mangarra Rd,5,h,8000000.0,VB,Sotheby's,13/05/2017,9.0,...,5.0,4.0,2079.0,464.3,1880.0,Boroondara,-37.81790,145.06940,Southern Metropolitan,3265.0
11033,14179,Toorak,13 Toorak Av,4,h,5733000.0,S,Marshall,22/04/2017,4.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Southern Metropolitan,7217.0
11765,15130,Middle Park,204 Page St,6,h,5600000.0,PI,Marshall,3/06/2017,3.0,...,4.0,2.0,472.0,328.0,1915.0,Port Phillip,-37.85231,144.96373,Southern Metropolitan,2019.0
12219,15696,Hawthorn,49 Lisson Gr,4,h,7650000.0,S,Abercromby's,17/06/2017,5.3,...,2.0,4.0,1690.0,284.0,1863.0,Boroondara,-37.82652,145.03052,Southern Metropolitan,11308.0
12447,16003,Toorak,21 Iona Av,4,h,6460000.0,S,RT,17/06/2017,4.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Southern Metropolitan,7217.0
12481,16048,Armadale,9 Alleyne Av,5,h,5925000.0,S,Marshall,24/06/2017,6.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Southern Metropolitan,4836.0
15270,19583,Mulgrave,35 Bevis St,3,h,9000000.0,PI,Hall,29/07/2017,18.8,...,1.0,1.0,744.0,117.0,1960.0,Monash,-37.93168,145.16126,South-Eastern Metropolitan,7113.0
16113,20684,Middle Park,136 Page St,5,h,6400000.0,S,Marshall,9/09/2017,3.0,...,2.0,1.0,553.0,308.0,1920.0,NaN,-37.84908,144.95753,Southern Metropolitan,2019.0
16308,20924,Armadale,42 Hampden Rd,4,h,6800000.0,VB,Marshall,16/09/2017,6.3,...,2.0,2.0,NaN,NaN,NaN,NaN,-37.85801,145.01383,Southern Metropolitan,4836.0
16586,21310,Kew,5 Stoke Av,5,h,5580000.0,SP,Marshall,16/09/2017,5.4,...,5.0,2.0,NaN,414.0,2007.0,NaN,-37.80749,145.05853,Southern Metropolitan,10331.0
18073,23154,Glen Iris,1 Anthony St,5,h,5770000.0,S,Marshall,26/08/2017,7.3,...,3.0,2.0,NaN,638.0,2011.0,NaN,-37.86048,145.04870,Southern Metropolitan,10412.0

In [7]:
df.groupby('Method')['Distance'].mean()

Method
PI     9.656418
S     10.718233
SA    12.369531
SP    10.612516
VB     8.550295
Name: Distance, dtype: float64

In [8]:
df['Method'].value_counts()

S     12034
SP     2349
PI     2189
VB     1696
SA      128
Name: Method, dtype: int64

In [9]:
df['Method'].unique()

array(['S', 'SP', 'PI', 'VB', 'SA'], dtype=object)

In [10]:
df['MT'] = df['Method'] + ' _ ' + df['Type']
df

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,MT
0,1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0,S _ h
1,2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,S _ h
2,4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0,SP _ h
3,5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0,PI _ h
4,6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0,VB _ h
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18391,23540,Williamstown,8/2 Thompson St,2,t,622500.0,SP,Greg,26/08/2017,6.8,...,1.0,NaN,89.0,2010.0,NaN,-37.86393,144.90484,Western Metropolitan,6380.0,SP _ t
18392,23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0,PI _ h
18393,23544,Yallambie,17 Amaroo Wy,4,h,1100000.0,S,Buckingham,26/08/2017,12.7,...,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0,S _ h
18394,23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0,SP _ h
18395,23546,Yarraville,33 Freeman St,4,h,1050000.0,VB,Village,26/08/2017,6.3,...,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0,VB _ h

In [11]:
df.groupby('Method')['Distance'].aggregate(lambda x: x.sum() / len(x))

Method
PI     9.656418
S     10.717343
SA    12.369531
SP    10.612516
VB     8.550295
Name: Distance, dtype: float64

In [12]:
animals = ['Bear', 'Mosse', 'Lion']

In [13]:
p_animals = pd.Series(animals)
p_animals

0     Bear
1    Mosse
2     Lion
dtype: object

In [14]:
animals = {
    'n1':'Bear',
    'n2':'Moose'
}

In [15]:
p_animals = pd.Series(animals)
p_animals

n1     Bear
n2    Moose
dtype: object

In [16]:
p_animals.index

Index(['n1', 'n2'], dtype='object')

In [17]:
df.loc[56:123, ['Method']]

    Method
56       S
57       S
58      VB
59      VB
60      VB
..     ...
119     PI
120      S
121      S
122      S
123      S

[68 rows x 1 columns]

In [18]:
df.drop(5, inplace = True)

In [19]:
df

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,MT
0,1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0,S _ h
1,2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,S _ h
2,4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0,SP _ h
3,5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0,PI _ h
4,6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0,VB _ h
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18391,23540,Williamstown,8/2 Thompson St,2,t,622500.0,SP,Greg,26/08/2017,6.8,...,1.0,NaN,89.0,2010.0,NaN,-37.86393,144.90484,Western Metropolitan,6380.0,SP _ t
18392,23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0,PI _ h
18393,23544,Yallambie,17 Amaroo Wy,4,h,1100000.0,S,Buckingham,26/08/2017,12.7,...,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0,S _ h
18394,23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0,SP _ h
18395,23546,Yarraville,33 Freeman St,4,h,1050000.0,VB,Village,26/08/2017,6.3,...,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0,VB _ h

In [20]:
df2 = df[:]
df2

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,MT
0,1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0,S _ h
1,2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,S _ h
2,4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0,SP _ h
3,5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0,PI _ h
4,6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0,VB _ h
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18391,23540,Williamstown,8/2 Thompson St,2,t,622500.0,SP,Greg,26/08/2017,6.8,...,1.0,NaN,89.0,2010.0,NaN,-37.86393,144.90484,Western Metropolitan,6380.0,SP _ t
18392,23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0,PI _ h
18393,23544,Yallambie,17 Amaroo Wy,4,h,1100000.0,S,Buckingham,26/08/2017,12.7,...,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0,S _ h
18394,23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0,SP _ h
18395,23546,Yarraville,33 Freeman St,4,h,1050000.0,VB,Village,26/08/2017,6.3,...,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0,VB _ h

In [21]:
df2.columns

Index(['Unnamed: 0', 'Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method',
       'SellerG', 'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom',
       'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea',
       'Lattitude', 'Longtitude', 'Regionname', 'Propertycount', 'MT'],
      dtype='object')

In [22]:
df.describe()

,Unnamed: 0,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,18395.000000,18395.000000,1.839500e+04,18394.000000,18394.000000,14926.000000,14924.000000,14819.000000,13602.000000,7762.000000,8958.000000,15063.000000,15063.000000,18394.000000
mean,11827.429465,2.935091,1.056704e+06,10.390415,3107.142329,2.913105,1.538529,1.615629,558.144096,151.220219,1965.879996,-37.809849,144.996338,7518.165489
std,6800.337136,0.958203,6.419385e+05,6.008931,95.003116,0.964645,0.689320,0.955856,3987.471854,519.188596,37.013261,0.081155,0.106379,4488.464459
min,1.000000,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,5937.500000,2.000000,6.330000e+05,6.300000,3046.000000,2.000000,1.000000,1.000000,176.250000,93.000000,1950.000000,-37.858100,144.931185,4294.000000
50%,11821.000000,3.000000,8.800000e+05,9.700000,3085.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.803600,145.000930,6567.000000
75%,17734.500000,3.000000,1.302000e+06,13.300000,3149.000000,3.000000,2.000000,2.000000,651.000000,174.000000,2000.000000,-37.756250,145.060000,10331.000000
max,23546.000000,12.000000,9.000000e+06,48.100000,3978.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18395 entries, 0 to 18395
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     18395 non-null  int64
 1   Suburb         18395 non-null  object
 2   Address        18395 non-null  object
 3   Rooms          18395 non-null  int64
 4   Type           18395 non-null  object
 5   Price          18395 non-null  float64
 6   Method         18395 non-null  object
 7   SellerG        18395 non-null  object
 8   Date           18395 non-null  object
 9   Distance       18394 non-null  float64
 10  Postcode       18394 non-null  float64
 11  Bedroom2       14926 non-null  float64
 12  Bathroom       14924 non-null  float64
 13  Car            14819 non-null  float64
 14  Landsize       13602 non-null  float64
 15  BuildingArea   7762 non-null   float64
 16  YearBuilt      8958 non-null   float64
 17  CouncilArea    12232 non-null  object
 18  Lattitude      15063 non-null  float64
 19  Longtitude     15063 non-null  float64
 20  Regionname     18394 non-null  object
 21  Propertycount  18394 non-null  float64
 22  MT             18395 non-null  object
dtypes: float64(12), int64(2), object(9)
memory usage: 3.4+ MB

In [24]:
df[df['Distance'] > 40]

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,MT
11143,14313,Clyde North,11 Riverbank Cl,4,h,689000.0,SP,Harcourts,1/07/2017,43.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eastern Victoria,2987.0,SP _ h
11205,14389,Gisborne,3 Sansom St,4,h,521000.0,SP,Raine,1/07/2017,45.9,...,2.0,978.0,144.0,1980.0,Macedon Ranges,-37.49642,144.60119,Northern Victoria,3376.0,SP _ h
11234,14426,Healesville,15A Westmount Rd,3,h,650000.0,SP,McGrath,1/07/2017,45.2,...,4.0,724.0,156.6,2009.0,Yarra Ranges,-37.64685,145.52635,Northern Victoria,3307.0,SP _ h
11820,15198,Pakenham,31 Azalea Av,4,h,510000.0,SP,Ray,3/06/2017,47.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eastern Victoria,17384.0,SP _ h
12181,15645,Gisborne,60 Hamilton St,3,h,540000.0,SA,McDonald,17/06/2017,45.9,...,2.0,665.0,110.0,1930.0,Macedon Ranges,-37.48701,144.58567,Northern Victoria,3376.0,SA _ h
12266,15761,Langwarrin,6/30 Warrenwood Pl,2,u,400000.0,SP,Mindacom,17/06/2017,41.0,...,1.0,196.0,NaN,2012.0,Frankston,-38.16439,145.19780,Eastern Victoria,8743.0,SP _ u
12793,16473,Pakenham,69 Willowtree Dr,4,h,410500.0,S,C21,24/06/2017,47.3,...,2.0,425.0,NaN,NaN,Cardinia,-38.07474,145.45376,Eastern Victoria,17384.0,S _ h
12831,16518,Riddells Creek,53 Bluegum Cct,4,h,817000.0,S,Raine,24/06/2017,47.4,...,4.0,1459.0,272.4,2011.0,Macedon Ranges,-37.45709,144.68999,Northern Victoria,1475.0,S _ h
12832,16519,Riddells Creek,2 Dwyer Ct,4,h,967500.0,S,Keatings,24/06/2017,47.4,...,NaN,NaN,NaN,NaN,NaN,-37.45310,144.67336,Northern Victoria,1475.0,S _ h
13063,16818,Clyde North,15 Palomino Av,4,h,635000.0,SA,O'Brien,27/05/2017,43.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eastern Victoria,2987.0,SA _ h
13166,16946,Gisborne,4/7 Francis Cr,3,h,470000.0,PI,Raine,27/05/2017,45.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Victoria,3376.0,PI _ h
13711,17627,Langwarrin,11 Lang Rd,3,h,500000.0,S,C21,8/07/2017,41.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eastern Victoria,8743.0,S _ h
13953,17930,Bullengarook,31 Carrolls La,3,h,535000.0,S,Keatings,12/08/2017,45.9,...,0.0,4000.0,NaN,NaN,Macedon Ranges,-37.50087,144.48571,Northern Victoria,249.0,S _ h
14057,18052,Gisborne,42 Kilmore Rd,3,h,775000.0,S,Raine,12/08/2017,45.9,...,4.0,1290.0,231.0,1988.0,Macedon Ranges,-37.48381,144.60052,Northern Victoria,3376.0,S _ h
14132,18142,Langwarrin,5 Athol Ct,3,h,650000.0,VB,O'Brien,12/08/2017,41.0,...,2.0,1060.0,NaN,NaN,Frankston,-38.15752,145.19127,Eastern Victoria,8743.0,VB _ h
14133,18143,Langwarrin,24 Lang Rd,2,h,482000.0,S,Community,12/08/2017,41.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eastern Victoria,8743.0,S _ h
14447,18531,Gisborne,21 Braeside Rd,4,h,807000.0,S,Raine,15/07/2017,45.9,...,3.0,40468.0,NaN,NaN,Macedon Ranges,-37.50929,144.56444,Northern Victoria,3376.0,S _ h
14448,18532,Gisborne,1/12 Rodney St,3,h,426000.0,S,Raine,15/07/2017,45.9,...,1.0,412.0,103.0,1950.0,Macedon Ranges,-37.49175,144.59565,Northern Victoria,3376.0,S _ h
14557,18668,Officer,24 Henrietta Av,4,h,559000.0,SP,Ray,15/07/2017,43.3,...,2.0,480.0,NaN,2015.0,Cardinia,-38.07054,145.42554,Eastern Victoria,2768.0,SP _ h
14558,18671,Pakenham,3 Cottage Lk,3,h,470000.0,S,Ray,15/07/2017,47.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eastern Victoria,17384.0,S _ h
14559,18672,Pakenham,4 Toorang Ct,4,h,435000.0,S,C21,15/07/2017,47.3,...,2.0,553.0,553.0,2005.0,Cardinia,-38.08699,145.48273,Eastern Victoria,17384.0,S _ h
14848,19039,Langwarrin,17/165 North Rd,3,u,447000.0,S,hockingstuart,22/07/2017,41.0,...,2.0,230.0,102.0,2002.0,Frankston,-38.16404,145.18781,Eastern Victoria,8743.0,S _ u
14849,19040,Langwarrin,67 Union Rd,4,h,900000.0,S,HAR,22/07/2017,41.0,...,6.0,2026.0,NaN,NaN,Frankston,-38.15575,145.19516,Eastern Victoria,8743.0,S _ h
14895,19102,Pakenham,1 Loxton Wy,4,h,643500.0,S,C21,22/07/2017,47.3,...,2.0,600.0,300.0,2010.0,Cardinia,-38.07583,145.43698,Eastern Victoria,17384.0,S _ h
15236,19540,Langwarrin,2 Gianna Wy,3,h,565500.0,S,O'Brien,29/07/2017,41.0,...,2.0,361.0,NaN,NaN,Frankston,-38.13673,145.21616,Eastern Victoria,8743.0,S _ h
15668,20083,Langwarrin,3/9 Margaret St,3,h,564000.0,S,hockingstuart,3/09/2017,41.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eastern Victoria,8743.0,S _ h
15712,20139,New Gisborne,28 Dalray Cr,4,h,690000.0,S,Raine,3/09/2017,48.1,...,2.0,NaN,175.0,2002.0,NaN,-37.46659,144.60241,Northern Victoria,849.0,S _ h
16007,20538,Gisborne,15 Morilla Ct,3,h,690000.0,VB,Raine,9/09/2017,45.9,...,2.0,2189.0,NaN,NaN,NaN,-37.50624,144.58134,Northern Victoria,3376.0,VB _ h
16008,20539,Gisborne,204 Panorama Dr,4,h,780000.0,S,Raine,9/09/2017,45.9,...,2.0,20200.0,189.0,1985.0,NaN,-37.49674,144.62618,Northern Victoria,3376.0,S _ h
16508,21197,Gisborne,13/109 Aitken St,3,h,500000.0,SP,Raine,16/09/2017,45.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Victoria,3376.0,SP _ h
16509,21198,Gisborne,6 Morand St,4,h,700000.0,S,Raine,16/09/2017,45.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Victoria,3376.0,S _ h
16510,21199,Gisborne,7 Wyralla Cr,6,h,650000.0,SP,Raine,16/09/2017,45.9,...,2.0,1301.0,NaN,NaN,NaN,-37.50733,144.58666,Northern Victoria,3376.0,SP _ h
16807,21590,Wallan,14 Danaher Av,3,h,366000.0,S,Ray,16/09/2017,44.2,...,1.0,502.0,77.0,1978.0,NaN,-37.40853,144.97749,Northern Victoria,3988.0,S _ h
17177,22030,Pakenham,10 Eyre Pl,4,h,442000.0,S,C21,19/08/2017,47.3,...,2.0,NaN,177.0,2011.0,NaN,-38.05934,145.51137,Eastern Victoria,17384.0,S _ h
17657,22632,New Gisborne,71 Hamilton Rd,5,h,1355000.0,S,Raine,23/09/2017,48.1,...,5.0,44500.0,44515.0,NaN,NaN,-37.45392,144.58864,Northern Victoria,849.0,S _ h
17658,22634,New Gisborne,190 Station Rd,3,h,565000.0,S,Raine,23/09/2017,48.1,...,2.0,NaN,NaN,NaN,NaN,-37.46731,144.59558,Northern Victoria,849.0,S _ h
18165,23263,Langwarrin,83 Pindara Bvd,4,h,965000.0,PI,O'Brien,26/08/2017,41.0,...,6.0,869.0,264.0,2007.0,NaN,-38.14508,145.18787,Eastern Victoria,8743.0,PI _ h